Repository bosonprotocol/boson-protocol-contracts, pull requests merged in 2022-11, with the labels that each got.

#457 Add interfaceIds to addesses file
  addresses/137-polygon.json
  addresses/80001-mumbai-staging.json
Labels: deployed addresses

#462 Specify environment in scripts
  addresses/137-polygon-prod.json
  addresses/80001-mumbai-staging.json
  addresses/80001-mumbai-test.json
  docs/tasks.md
  hardhat.config.js
  package.json
  scripts/deploy-suite.js
  scripts/manage-roles.js
  scripts/upgrade-facets.js
  scripts/util/utils.js
Labels: enhancement

#452 Snapshot Gate example
  README.md
  contracts/example/SnapshotGate/SnapshotGate.sol
  contracts/example/SnapshotGate/support/ERC721.sol
  contracts/example/SnapshotGate/support/IERC721Metadata.sol
  contracts/example/SnapshotGate/support/IERC721Receiver.sol
  docs/example/SnapshotGate.md
  docs/examples.md
  docs/images/Boson_Protocol_V2_-_SnapshotGate_Example.png
  scripts/example/SnapshotGate/deploy-snapshot-gate.js
  test/example/SnapshotGateTest.js
Labels: Example

#468 Verify succesful upgrade - new actions after upgrade
  test/upgrade/2.0.0-2.1.0.js
Labels: enhancement

#471 Verify succesful upgrade - refactor
  hardhat.config.js
  scripts/deploy-suite.js
  scripts/upgrade-facets.js
  test/upgrade/00_config.js
  test/upgrade/01_generic.js
  test/upgrade/2.0.0-2.1.0.js
  test/util/upgrade.js
Labels: enhancement

#474 Script to upgrade client
  docs/local-development.md
  docs/tasks.md
  hardhat.config.js
  package.json
  scripts/upgrade-clients.js
Labels: enhancement
