Repository bosonprotocol/boson-protocol-contracts, pull requests merged in 2023-04, with the labels that each got.

#591 Prevent renounceOwnership
  contracts/protocol/clients/voucher/BosonVoucher.sol
  test/protocol/clients/BosonVoucherTest.js
Labels: bug, v2.2.0

#589 Use correct owner in burnPremintedVouchers
  contracts/protocol/clients/voucher/BosonVoucher.sol
  test/protocol/clients/BosonVoucherTest.js
Labels: bug, v2.2.0

#583 New tokenIds
  contracts/interfaces/clients/IBosonVoucher.sol
  contracts/mock/MockExchangeHandlerFacet.sol
  contracts/protocol/bases/BeaconClientBase.sol
  contracts/protocol/bases/OfferBase.sol
  contracts/protocol/clients/voucher/BosonVoucher.sol
  contracts/protocol/facets/ExchangeHandlerFacet.sol
  scripts/config/facet-deploy.js
  scripts/config/protocol-parameters.js
  scripts/util/deploy-protocol-handler-facets.js
  test/protocol/ExchangeHandlerTest.js
  test/protocol/FundsHandlerTest.js
  test/protocol/OfferHandlerTest.js
  test/protocol/OrchestrationHandlerTest.js
  test/protocol/clients/BosonVoucherTest.js
  test/util/utils.js
Labels: enhancement, v2.2.0

#595 Refactor tests
  scripts/util/split-unit-tests-into-chunks.js
  test/integration/01-update-account-roles-addresses.js
  test/integration/02-Upgraded-facet.js
  test/integration/03-DR-removes-the-seller-from-allowed-list.js
  test/integration/04-DR-removes-fees.js
  test/integration/seaport/seaport-integration.js
  test/protocol/AccountHandlerTest.js
  test/protocol/AgentHandlerTest.js
  test/protocol/BundleHandlerTest.js
  test/protocol/BuyerHandlerTest.js
  test/protocol/ConfigHandlerTest.js
  test/protocol/DisputeHandlerTest.js
  test/protocol/DisputeResolverHandlerTest.js
  test/protocol/ExchangeHandlerTest.js
  test/protocol/FundsHandlerTest.js
  test/protocol/GroupHandlerTest.js
  test/protocol/MetaTransactionsHandlerTest.js
  test/protocol/OfferHandlerTest.js
  test/protocol/OrchestrationHandlerTest.js
  test/protocol/PauseHandlerTest.js
  test/protocol/SellerHandlerTest.js
  test/protocol/TwinHandlerTest.js
  test/protocol/clients/BosonVoucherTest.js
  test/protocol/clients/ClientExternalAddressesTest.js
  test/upgrade/01_generic.js
  test/upgrade/2.0.0-2.1.0.js
  test/upgrade/clients/01_generic.js
  test/upgrade/clients/BosonVoucher-2.1.0-2.2.0.js
  test/util/mock.js
  test/util/test-chunks.txt
  test/util/utils.js
Labels: Refactor, v2.2.0

#597 Code coverage 2.2.0
  .github/workflows/ci.yaml
  .solcover.js
  contracts/interfaces/clients/IBosonVoucher.sol
  contracts/mock/Foreign20.sol
  contracts/protocol/clients/voucher/BosonVoucher.sol
  package.json
  scripts/config/revert-reasons.js
  test/access/AccessControllerTest.js
  test/protocol/ExchangeHandlerTest.js
  test/protocol/OfferHandlerTest.js
  test/protocol/OrchestrationHandlerTest.js
  test/protocol/PauseHandlerTest.js
  test/protocol/TwinHandlerTest.js
  test/protocol/clients/BosonVoucherTest.js
  test/util/utils.js
Labels: v2.2.0

#606 Upgrade hooks
  scripts/config/facet-deploy.js
  scripts/config/protocol-parameters.js
  scripts/upgrade-facets.js
  scripts/upgrade-hooks/2.2.0.js
  scripts/util/deploy-protocol-handler-facets.js
Labels: enhancement, v2.2.0

#498 Add tests upgrade to v2.2.0
  .prettierrc
  .solhint.json
  contracts/diamond/JewelerLib.sol
  contracts/diamond/facets/DiamondCutFacet.sol
  contracts/diamond/facets/DiamondLoupeFacet.sol
  contracts/example/SnapshotGate/support/ERC721.sol
  contracts/ext_libs/Address.sol
  contracts/ext_libs/Math.sol
  contracts/ext_libs/SafeERC20.sol
  contracts/interfaces/DAIAliases.sol
  contracts/interfaces/IERC1155.sol
  contracts/interfaces/IERC20.sol
  contracts/interfaces/IERC2981.sol
  contracts/interfaces/IERC721.sol
  contracts/interfaces/clients/IBosonVoucher.sol
  contracts/interfaces/diamond/IDiamondCut.sol
  contracts/interfaces/handlers/IBosonAccountHandler.sol
  contracts/interfaces/handlers/IBosonDisputeHandler.sol
  contracts/interfaces/handlers/IBosonExchangeHandler.sol
  contracts/interfaces/handlers/IBosonFundsHandler.sol
  contracts/interfaces/handlers/IBosonGroupHandler.sol
  contracts/interfaces/handlers/IBosonOfferHandler.sol
  contracts/mock/BosonToken.sol
  contracts/mock/Foreign20.sol
  contracts/mock/MockExchangeHandlerFacet.sol
  contracts/mock/MockForwarder.sol
  contracts/protocol/bases/BundleBase.sol
  contracts/protocol/bases/DisputeBase.sol
  contracts/protocol/bases/GroupBase.sol
  contracts/protocol/bases/ProtocolBase.sol
  contracts/protocol/bases/SellerBase.sol
  contracts/protocol/clients/voucher/BosonVoucher.sol
  contracts/protocol/facets/ConfigHandlerFacet.sol
  contracts/protocol/facets/DisputeHandlerFacet.sol
  contracts/protocol/facets/DisputeResolverHandlerFacet.sol
  contracts/protocol/facets/ExchangeHandlerFacet.sol
  contracts/protocol/facets/FundsHandlerFacet.sol
  contracts/protocol/facets/GroupHandlerFacet.sol
  contracts/protocol/facets/MetaTransactionsHandlerFacet.sol
  contracts/protocol/facets/OfferHandlerFacet.sol
  contracts/protocol/facets/OrchestrationHandlerFacet1.sol
  contracts/protocol/facets/PauseHandlerFacet.sol
  contracts/protocol/facets/SellerHandlerFacet.sol
  contracts/protocol/libs/FundsLib.sol
  package-lock.json
  package.json
  scripts/upgrade-facets.js
  scripts/util/diamond-utils.js
  test/protocol/OrchestrationHandlerTest.js
  test/protocol/ProtocolInitializationHandlerTest.js
  test/protocol/clients/BosonVoucherTest.js
  test/upgrade/00_config.js
  test/upgrade/01_generic.js
  test/upgrade/2.0.0-2.1.0.js
  test/upgrade/2.1.0-2.2.0.js
  test/upgrade/clients/BosonVoucher-2.1.0-2.2.0.js
  test/util/upgrade.js
  test/util/utils.js
Labels: v2.2.0
