Repository bosonprotocol/boson-protocol-contracts, pull requests merged in 2023-07, with the labels that each got.

#634 Boson voucher bug fixes
  .husky/pre-commit
  contracts/domain/BosonConstants.sol
  contracts/interfaces/clients/IBosonVoucher.sol
  contracts/mock/MockSimpleContract.sol
  contracts/protocol/clients/voucher/BosonVoucher.sol
  scripts/config/revert-reasons.js
  test/protocol/ExchangeHandlerTest.js
  test/protocol/SellerHandlerTest.js
  test/protocol/clients/BosonVoucherTest.js
Labels: v2.3.0

#652 Fix unsuccessful twin transfer
  contracts/protocol/facets/ExchangeHandlerFacet.sol
  test/protocol/ExchangeHandlerTest.js
  test/protocol/TwinHandlerTest.js
Labels: v2.3.0

#653 Check that the twin address is a contract
  contracts/mock/Foreign1155.sol
  contracts/mock/Foreign721.sol
  contracts/protocol/facets/ExchangeHandlerFacet.sol
  test/protocol/ExchangeHandlerTest.js
Labels: v2.3.0

#673 Add minimal resolution period
  contracts/interfaces/events/IBosonConfigEvents.sol
  contracts/interfaces/handlers/IBosonConfigHandler.sol
  contracts/interfaces/handlers/IBosonOfferHandler.sol
  contracts/interfaces/handlers/IBosonOrchestrationHandler.sol
  contracts/protocol/bases/OfferBase.sol
  contracts/protocol/facets/ConfigHandlerFacet.sol
  contracts/protocol/facets/OfferHandlerFacet.sol
  contracts/protocol/facets/OrchestrationHandlerFacet1.sol
  contracts/protocol/facets/ProtocolInitializationHandlerFacet.sol
  contracts/protocol/libs/ProtocolLib.sol
  scripts/config/protocol-parameters.js
  test/example/SnapshotGateTest.js
  test/protocol/ConfigHandlerTest.js
  test/protocol/OfferHandlerTest.js
  test/protocol/OrchestrationHandlerTest.js
  test/protocol/ProtocolInitializationHandlerTest.js
  test/util/mock.js
  test/util/utils.js
Labels: bug, v2.3.0

#684 Clean pending auth token during updateSeller call
  contracts/protocol/facets/SellerHandlerFacet.sol
  test/protocol/SellerHandlerTest.js
Labels: v2.3.0

#694 Limit gas when doing twin transfers
  contracts/domain/BosonConstants.sol
  contracts/mock/Foreign1155.sol
  contracts/mock/Foreign20.sol
  contracts/mock/Foreign721.sol
  contracts/protocol/facets/ExchangeHandlerFacet.sol
  test/protocol/ExchangeHandlerTest.js
Labels: bug, v2.3.0

#695 Resolve time conflict in redeemVoucher and expireVoucher
  contracts/protocol/facets/ExchangeHandlerFacet.sol
  test/integration/02-Upgraded-facet.js
  test/protocol/DisputeHandlerTest.js
  test/protocol/ExchangeHandlerTest.js
  test/protocol/FundsHandlerTest.js
  test/protocol/clients/BosonVoucherTest.js
  test/util/utils.js
Labels: bug, v2.3.0

#644 Unpause individual regions
  .github/workflows/ci.yaml
  contracts/domain/BosonConstants.sol
  contracts/interfaces/events/IBosonPauseEvents.sol
  contracts/interfaces/handlers/IBosonPauseHandler.sol
  contracts/protocol/facets/PauseHandlerFacet.sol
  scripts/config/revert-reasons.js
  test/protocol/PauseHandlerTest.js
  test/util/upgrade.js
Labels: v2.3.0

#592 Multiple collections per seller
  contracts/domain/BosonConstants.sol
  contracts/domain/BosonTypes.sol
  contracts/interfaces/IInitializableVoucherClone.sol
  contracts/interfaces/events/IBosonAccountEvents.sol
  contracts/interfaces/handlers/IBosonAccountHandler.sol
  contracts/interfaces/handlers/IBosonOfferHandler.sol
  contracts/interfaces/handlers/IBosonOrchestrationHandler.sol
  contracts/protocol/bases/OfferBase.sol
  contracts/protocol/bases/ProtocolBase.sol
  contracts/protocol/bases/SellerBase.sol
  contracts/protocol/clients/voucher/BosonVoucher.sol
  contracts/protocol/facets/ExchangeHandlerFacet.sol
  contracts/protocol/facets/OfferHandlerFacet.sol
  contracts/protocol/facets/OrchestrationHandlerFacet1.sol
  contracts/protocol/facets/SellerHandlerFacet.sol
  contracts/protocol/libs/ProtocolLib.sol
  scripts/config/revert-reasons.js
  scripts/domain/Collection.js
  scripts/domain/Offer.js
  test/domain/CollectionTest.js
  test/domain/OfferTest.js
  test/protocol/ExchangeHandlerTest.js
  test/protocol/MetaTransactionsHandlerTest.js
  test/protocol/OfferHandlerTest.js
  test/protocol/OrchestrationHandlerTest.js
  test/protocol/SellerHandlerTest.js
  test/protocol/clients/BosonVoucherTest.js
  test/util/mock.js
Labels: enhancement, v2.3.0

#635 Fix token gating
  README.md
  contracts/domain/BosonConstants.sol
  contracts/domain/BosonTypes.sol
  contracts/example/SnapshotGate/SnapshotGate.sol
  contracts/interfaces/handlers/IBosonExchangeHandler.sol
  contracts/interfaces/handlers/IBosonGroupHandler.sol
  contracts/interfaces/handlers/IBosonOrchestrationHandler.sol
  contracts/protocol/bases/BundleBase.sol
  contracts/protocol/bases/GroupBase.sol
  contracts/protocol/bases/OfferBase.sol
  contracts/protocol/bases/ProtocolBase.sol
  contracts/protocol/clients/voucher/BosonVoucher.sol
  contracts/protocol/facets/ExchangeHandlerFacet.sol
  contracts/protocol/facets/OfferHandlerFacet.sol
  contracts/protocol/libs/ProtocolLib.sol
  scripts/config/revert-reasons.js
  scripts/domain/Condition.js
  scripts/domain/Receipt.js
  test/domain/ConditionTest.js
  test/domain/ReceiptTest.js
  test/example/SnapshotGateTest.js
  test/protocol/ExchangeHandlerTest.js
  test/protocol/GroupHandlerTest.js
  test/protocol/OrchestrationHandlerTest.js
  test/util/mock.js
  test/util/upgrade.js
Labels: v2.3.0

#675 Remove protocol gas limits
  contracts/domain/BosonConstants.sol
  contracts/interfaces/clients/IBosonVoucher.sol
  contracts/interfaces/events/IBosonConfigEvents.sol
  contracts/interfaces/handlers/IBosonAccountHandler.sol
  contracts/interfaces/handlers/IBosonBundleHandler.sol
  contracts/interfaces/handlers/IBosonConfigHandler.sol
  contracts/interfaces/handlers/IBosonDisputeHandler.sol
  contracts/interfaces/handlers/IBosonExchangeHandler.sol
  contracts/interfaces/handlers/IBosonFundsHandler.sol
  contracts/interfaces/handlers/IBosonGroupHandler.sol
  contracts/interfaces/handlers/IBosonOfferHandler.sol
  contracts/interfaces/handlers/IBosonOrchestrationHandler.sol
  contracts/mock/MockExchangeHandlerFacet.sol
  contracts/protocol/bases/BundleBase.sol
  contracts/protocol/bases/GroupBase.sol
  contracts/protocol/clients/voucher/BosonVoucher.sol
  contracts/protocol/facets/BundleHandlerFacet.sol
  contracts/protocol/facets/ConfigHandlerFacet.sol
  contracts/protocol/facets/DisputeHandlerFacet.sol
  contracts/protocol/facets/DisputeResolverHandlerFacet.sol
  contracts/protocol/facets/ExchangeHandlerFacet.sol
  contracts/protocol/facets/FundsHandlerFacet.sol
  contracts/protocol/facets/GroupHandlerFacet.sol
  contracts/protocol/facets/OfferHandlerFacet.sol
  contracts/protocol/facets/OrchestrationHandlerFacet1.sol
  docs/limit-estimation.md
  hardhat.config.js
  scripts/config/limit-estimation.js
  scripts/config/revert-reasons.js
  scripts/migrations/migrate_2.2.1.js
  scripts/util/estimate-configurations.js
  test/integration/seaport/utils.js
  test/protocol/BundleHandlerTest.js
  test/protocol/ConfigHandlerTest.js
  test/protocol/DisputeHandlerTest.js
  test/protocol/DisputeResolverHandlerTest.js
  test/protocol/ExchangeHandlerTest.js
  test/protocol/FundsHandlerTest.js
  test/protocol/GroupHandlerTest.js
  test/protocol/MetaTransactionsHandlerTest.js
  test/protocol/OfferHandlerTest.js
  test/protocol/ProtocolInitializationHandlerTest.js
  test/protocol/clients/BosonVoucherTest.js
  test/upgrade/00_config.js
  test/util/upgrade.js
Labels: v2.3.0

#656 Fix twin inefficiencies
  contracts/domain/BosonConstants.sol
  contracts/protocol/bases/GroupBase.sol
  contracts/protocol/bases/TwinBase.sol
  contracts/protocol/facets/ExchangeHandlerFacet.sol
  contracts/protocol/facets/ProtocolInitializationHandlerFacet.sol
  contracts/protocol/facets/TwinHandlerFacet.sol
  contracts/protocol/libs/ProtocolLib.sol
  package-lock.json
  scripts/config/revert-reasons.js
  test/protocol/ExchangeHandlerTest.js
  test/protocol/ProtocolInitializationHandlerTest.js
  test/util/utils.js
Labels: v2.3.0

#703 Clone vouchers using create2
  contracts/domain/BosonConstants.sol
  contracts/protocol/bases/SellerBase.sol
  contracts/protocol/facets/ConfigHandlerFacet.sol
  contracts/protocol/facets/ProtocolInitializationHandlerFacet.sol
  contracts/protocol/facets/SellerHandlerFacet.sol
  contracts/protocol/libs/ProtocolLib.sol
  hardhat.config.js
  scripts/deploy-suite.js
  scripts/util/deploy-protocol-clients.js
  scripts/util/estimate-limits.js
  test/integration/01-update-account-roles-addresses.js
  test/integration/04-DR-removes-fees.js
  test/protocol/BuyerHandlerTest.js
  test/protocol/ConfigHandlerTest.js
  test/protocol/ExchangeHandlerTest.js
  test/protocol/FundsHandlerTest.js
  test/protocol/OfferHandlerTest.js
  test/protocol/OrchestrationHandlerTest.js
  test/protocol/ProtocolInitializationHandlerTest.js
  test/protocol/SellerHandlerTest.js
  test/protocol/clients/BosonVoucherTest.js
  test/util/upgrade.js
  test/util/utils.js
Labels: enhancement, v2.3.0

#698 More flexible getAvailableFunds
  contracts/domain/BosonConstants.sol
  contracts/interfaces/handlers/IBosonFundsHandler.sol
  contracts/mock/Foreign20.sol
  contracts/protocol/facets/FundsHandlerFacet.sol
  test/protocol/FundsHandlerTest.js
  test/protocol/clients/BosonVoucherTest.js
  test/upgrade/clients/BosonVoucher-2.1.0-2.2.0.js
  test/util/upgrade.js
Labels: v2.3.0

#686 v2.3.0 scripts: migrations, dry-run, detect changes
  docs/local-development.md
  docs/tasks.md
  hardhat.config.js
  package-lock.json
  package.json
  scripts/migrations/dry-run.js
  scripts/migrations/migrate_2.3.0.js
  scripts/upgrade-facets.js
  scripts/util/detect-changed-contracts.js
  scripts/util/utils.js
  test/example/SnapshotGateTest.js
  test/protocol/ProtocolInitializationHandlerTest.js
  test/util/constants.js
Labels: v2.3.0
