Repository bosonprotocol/boson-protocol-contracts, pull requests merged in 2023-08, with the labels that each got.

#748 Remediate [SHF-01M] Incorrect Iterator Usage
  contracts/protocol/facets/SellerHandlerFacet.sol
  test/protocol/SellerHandlerTest.js
Labels: bug, v2.3.0

#752 Remediate [EHF-01C] Inefficient mapping Lookups
  contracts/protocol/facets/ExchangeHandlerFacet.sol
Labels: Refactor, v2.3.0

#749 Remediate [BVR-01C] Potential Legibility Optimization
  contracts/protocol/clients/voucher/BosonVoucher.sol
  test/protocol/OrchestrationHandlerTest.js
  test/protocol/SellerHandlerTest.js
Labels: enhancement, v2.3.0

#754 Remediate [OBE-01C] Illegible Representation of Limitation
  contracts/protocol/bases/OfferBase.sol
Labels: enhancement, v2.3.0

#718 Replace approve for forceApprove on BosonVoucher
  .solhint.json
  contracts/access/AccessControl.sol
  contracts/example/SnapshotGate/SnapshotGate.sol
  contracts/example/SnapshotGate/support/ERC721.sol
  contracts/ext_libs/Address.sol
  contracts/ext_libs/Math.sol
  contracts/ext_libs/SafeERC20.sol
  contracts/ext_libs/Strings.sol
  contracts/mock/MockExchangeHandlerFacet.sol
  contracts/mock/USDT.sol
  contracts/protocol/clients/voucher/BosonVoucher.sol
  contracts/protocol/facets/ExchangeHandlerFacet.sol
  contracts/protocol/libs/FundsLib.sol
  hardhat.config.js
  scripts/config/revert-reasons.js
  test/protocol/FundsHandlerTest.js
  test/protocol/clients/BosonVoucherTest.js
Labels: v2.3.0

#753 Remediate [BVR-06M] Insufficient Protection of Contract Assets
  contracts/domain/BosonConstants.sol
  contracts/interfaces/clients/IBosonVoucher.sol
  contracts/protocol/clients/voucher/BosonVoucher.sol
  scripts/config/revert-reasons.js
  test/protocol/clients/BosonVoucherTest.js
Labels: bug, v2.3.0

#779 Remediate [EHF-03M] Bypass of Token Specific Conditions
  .husky/pre-commit
  contracts/domain/BosonConstants.sol
  contracts/domain/BosonTypes.sol
  contracts/interfaces/handlers/IBosonGroupHandler.sol
  contracts/interfaces/handlers/IBosonOrchestrationHandler.sol
  contracts/protocol/bases/GroupBase.sol
  contracts/protocol/facets/ExchangeHandlerFacet.sol
  contracts/protocol/facets/GroupHandlerFacet.sol
  docs/images/Boson_Protocol_V2_-_Domain_Model.png
  scripts/config/revert-reasons.js
  scripts/domain/Condition.js
  scripts/domain/GatingType.js
  test/domain/ConditionTest.js
  test/example/SnapshotGateTest.js
  test/protocol/ExchangeHandlerTest.js
  test/protocol/GroupHandlerTest.js
  test/util/mock.js
Labels: bug, Refactor, v2.3.0

#747 Remmediate [PIH-01M] Inexistent Support of Manual Seller Configuration
  contracts/interfaces/handlers/IBosonAccountHandler.sol
  contracts/protocol/facets/SellerHandlerFacet.sol
  test/protocol/SellerHandlerTest.js
  test/util/utils.js
Labels: v2.3.0

#755 Optimize iterators
  contracts/example/SnapshotGate/SnapshotGate.sol
  contracts/mock/MockExchangeHandlerFacet.sol
  contracts/protocol/bases/BundleBase.sol
  contracts/protocol/bases/GroupBase.sol
  contracts/protocol/bases/TwinBase.sol
  contracts/protocol/clients/voucher/BosonVoucher.sol
  contracts/protocol/facets/DisputeHandlerFacet.sol
  contracts/protocol/facets/DisputeResolverHandlerFacet.sol
  contracts/protocol/facets/ExchangeHandlerFacet.sol
  contracts/protocol/facets/FundsHandlerFacet.sol
  contracts/protocol/facets/GroupHandlerFacet.sol
  contracts/protocol/facets/MetaTransactionsHandlerFacet.sol
  contracts/protocol/facets/OfferHandlerFacet.sol
  contracts/protocol/facets/PauseHandlerFacet.sol
  contracts/protocol/facets/ProtocolInitializationHandlerFacet.sol
  contracts/protocol/facets/SellerHandlerFacet.sol
Labels: enhancement, v2.3.0

#759 Raise dispute only once even if multiple twin transfers fail
  contracts/protocol/facets/ExchangeHandlerFacet.sol
  test/protocol/ExchangeHandlerTest.js
Labels: bug, Refactor, v2.3.0

#765 Add the missing reentrancy guard
  contracts/protocol/facets/MetaTransactionsHandlerFacet.sol
Labels: bug, v2.3.0

#771 Remediate malformed return during the twin transfer
  contracts/mock/Foreign1155.sol
  contracts/mock/Foreign20.sol
  contracts/mock/Foreign721.sol
  contracts/protocol/facets/ExchangeHandlerFacet.sol
  test/protocol/ExchangeHandlerTest.js
Labels: bug, v2.3.0

#772 Remediate returnbomb during a twin transfer
  contracts/mock/Foreign1155.sol
  contracts/mock/Foreign721.sol
  contracts/protocol/facets/ExchangeHandlerFacet.sol
  test/protocol/ExchangeHandlerTest.js
Labels: bug, v2.3.0

#764 Estimate the twin transfer gas limits
  contracts/domain/BosonConstants.sol
  contracts/protocol/facets/ExchangeHandlerFacet.sol
  docs/tasks.md
  docs/twin-transfer-limits.md
  scripts/util/estimate-twin-transfer-limits.js
Labels: v2.3.0
