Repository bosonprotocol/boson-protocol-contracts, pull requests merged in 2023-05, with the labels that each got.

#621 Add upgrade tests and migrations to v2.2.1
  contracts/protocol/facets/ProtocolInitializationHandlerFacet.sol
  hardhat.config.js
  package.json
  scripts/config/facet-deploy.js
  scripts/deploy-suite.js
  scripts/domain/Seller.js
  scripts/migrations/migrate_2.2.1.js
  scripts/upgrade-clients.js
  scripts/upgrade-facets.js
  scripts/util/deploy-protocol-handler-facets.js
  scripts/util/diamond-utils.js
  scripts/util/utils.js
  test/protocol/MetaTransactionsHandlerTest.js
  test/protocol/ProtocolInitializationHandlerTest.js
  test/upgrade/00_config.js
  test/upgrade/01_generic.js
  test/upgrade/2.0.0-2.1.0.js
  test/upgrade/2.1.0-2.2.0.js
  test/upgrade/2.2.0-2.2.1.js
  test/util/upgrade.js
Labels: v2.2.1

#624 Fix the bug in update seller
  contracts/protocol/facets/SellerHandlerFacet.sol
  test/protocol/SellerHandlerTest.js
Labels: bug, v2.2.1

#607 This cleans up some local variable names
  contracts/protocol/bases/BeaconClientBase.sol
  contracts/protocol/bases/BundleBase.sol
  contracts/protocol/bases/ClientBase.sol
  contracts/protocol/bases/ClientExternalAddressesBase.sol
  contracts/protocol/facets/ExchangeHandlerFacet.sol
  contracts/protocol/libs/BeaconClientLib.sol
  contracts/protocol/libs/ClientLib.sol
Labels: enhancement, v2.3.0

#620 This should quieten a couple of warnings
  contracts/protocol/facets/ExchangeHandlerFacet.sol
Labels: v2.3.0

#641 Improve coverage CI report with coveralls
  .github/workflows/ci.yaml
  .husky/pre-commit
  .solcover.js
  README.md
  contracts/protocol/clients/voucher/BosonVoucher.sol
  package-lock.json
  package.json
  test/protocol/clients/BosonVoucherTest.js
Labels: v2.3.0
